version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: stocks_db
      POSTGRES_USER: stocks_user
      POSTGRES_PASSWORD: stocks_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - stocks_network

  backend:
    build: .
    container_name: stocks-app
    depends_on:
      - db
    environment:
      DJANGO_DEBUG: "False"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,stocks-app,nginx"
      DJANGO_DATABASE_ENGINE: "django.db.backends.postgresql"
      DJANGO_DATABASE_NAME: stocks_db
      DJANGO_DATABASE_USER: stocks_user
      DJANGO_DATABASE_PASSWORD: stocks_pass
      DJANGO_DATABASE_HOST: db
      DJANGO_DATABASE_PORT: "5432"
    volumes:
      - static_volume:/app/static
    expose:
      - "8000"
    networks:
      - stocks_network

  nginx:
    image: nginx:latest
    container_name: stocks-nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - stocks_network

volumes:
  postgres_data:
  static_volume:

networks:
  stocks_network:
    driver: bridge