name: Deploy Django App via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (if any)
        run: |
          if [ -f "manage.py" ]; then
            python manage.py test || echo "Some tests failed"
          else
            echo "No manage.py found. Skipping tests."
          fi

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Обновляем проект"
            cd /root/my_crud_project/stocks_products
            git pull origin main
            source ../venv/bin/activate

            pip install -r requirements.txt

            # Убедитесь, что мы в корневой директории проекта
            cd /root/my_crud_project/stocks_products

            python manage.py migrate
            python manage.py collectstatic --noinput --clear
            systemctl restart gunicorn
